seed: 2952
workers: 32

# Architecture and MoCo parameters
arch: vit_s
moco_dim: 256
moco_mlp_dim: 4096
moco_t: 0.2

# For SSL training
ssl_batch_size: 256
ssl_optimizer: adamw
ssl_lr: 1.5e-3
ssl_wd: 0.05
ssl_momentum: 0.9
ssl_epochs: 300
ssl_warmup_epochs: 20
ssl_moco_m_cos: true
ssl_crop_min: 0.2
ssl_moco_m: 0.99
ssl_print_freq: 10
ssl_save_freq: 50

# For linear probing
lp_batch_size: 1024
lp_epochs: 100
lp_lr: 3e-3
lp_wd: 0.05
lp_print_freq: 5